baseURL = "https://www.arts4kidz.org/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Donate"
url = "/donate"
weight = 3
[[menu.main]]
name = "Board of Directors"
url = "/gallery"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 2
