baseURL = "https://www.arts4kidz.org/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Donate"
weight = 6
[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 3
