baseURL = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Donate"
url = "/donate"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 2